export default [
  { label: 'Antrim', value: 'antrim'},
  { label: 'Armagh', value: 'armagh' },
  { label: 'Carlow', value: 'carlow' },
  { label: 'Cavan', value: 'cavan' },
  { label: 'Clare', value: 'clare' },
  { label: 'Cork', value: 'cork' },
  { label: 'Derry', value: 'derry' },
  { label: 'Donegal', value: 'donegal' },
  { label: 'Down', value: 'down' },
  { label: 'Dublin', value: 'dublin' },
  { label: 'Fermanagh', value: 'fermnagh' },
  { label: 'Galway', value: 'galway' },
  { label: 'Kerry', value: 'kerry' },
  { label: 'Kildare', value: 'kildare' },
  { label: 'Kilkenny', value: 'kilkenny' },
  { label: 'Laois', value: 'laois' },
  { label: 'Leitrim', value: 'leitrim' },
  { label: 'Limerick', value: 'limerick' },
  { label: 'Longford', value: 'longford' },
  { label: 'Louth', value: 'louth' },
  { label: 'Mayo', value: 'mayo' },
  { label: 'Meath', value: 'meath' },
  { label: 'Monaghan', value: 'monaghan' },
  { label: 'Offaly', value: 'offaly' },
  { label: 'Roscommon', value: 'roscommon' },
  { label: 'Sligo', value: 'sligo'},
  { label: 'Tipperary', value: 'tipperary'},
  { label: 'Tyrone', value: 'tyrone' },
  { label: 'Waterford', value: 'waterford'},
  { label: 'Westmeath', value: 'westmeath'},
  { label: 'Wexford', value: 'wexford' },
  { label: 'Wicklow', value: 'wicklow' },
];